activities_data = {
    "Productive": {
        "Learning & Skill-Building": [
            "Take a free online course (e.g., Coursera, edX)",
            "Learn a new language using Duolingo",
            "Practice a new skill like coding or video editing",
            "Read a non-fiction or self-help book",
            "Write in a journal (gratitude, goals, thoughts)",
            "Watch educational YouTube videos or TED Talks",
            "Start a blog or personal website",
            "Learn about digital marketing or SEO",
            "Take up graphic design or illustration",
            "Learn photography and editing",
            "Complete a project on GitHub",
            "Read articles on topics you want to explore more",
            "Take notes from a podcast or audiobook",
            "Learn a new cooking technique or recipe",
            "Experiment with DIY home improvement projects",
            "Learn a new instrument or improve your current skills",
            "Master Excel or Google Sheets for data management",
            "Practice public speaking or record your own speeches",
            "Learn to build websites or mobile apps",
            "Join a virtual book club or reading group",
            "Attend a live webinar or online event",
            "Create an online course and teach others",
            "Learn about stock market investing or personal finance",
            "Take up public speaking or debate",
            "Start a fitness routine with bodyweight exercises",
            "Write an e-book or guide on a topic you're passionate about",
            "Develop a mobile app or game idea",
            "Take up coding challenges on platforms like HackerRank",
            "Volunteer to help others learn a skill",
            "Learn how to use design software like Adobe Photoshop",
            "Watch documentaries on topics of interest",
            "Start a podcast or YouTube channel to share knowledge",
            "Create a personal development plan and track progress",
            "Practice mindfulness techniques like meditation or yoga",
            "Set a career goal and create a roadmap to achieve it",
            "Learn the basics of 3D modeling or animation",
            "Create a vision board for your career and personal goals",
            "Take up a new hobby like woodworking or crafting"
        ],
        "Personal Organization": [
            "Clean or declutter your room or workspace",
            "Organize files (Google Drive, desktop, photos)",
            "Update your resume or LinkedIn profile",
            "Create a personal budget or financial plan",
            "Plan your week or set monthly goals",
            "Tidy up your emails and unsubscribe from unwanted lists",
            "Use a task manager app like Todoist or Trello",
            "Create a meal plan for the week",
            "Organize your photo gallery on your phone",
            "Set up a home filing system for important documents",
            "Sort through old clothes and donate what you don't need",
            "Use a password manager to organize your passwords",
            "Declutter your digital workspace (remove unused apps)",
            "Set up a savings account or emergency fund",
            "Rearrange your furniture to improve your space",
            "Create a morning routine for productivity",
            "Set up a weekly calendar to plan your time",
            "Track your expenses using an app or spreadsheet",
            "Create a weekly meal prep plan for the week",
            "Set goals for your health and fitness and track them",
            "Clean out your car and organize it",
            "Organize your books, notes, or journals",
            "Create a system for handling incoming mail",
            "Set up a system for managing your bills",
            "Create a home inventory list of valuables",
            "Make a packing list for upcoming trips",
            "Start a bullet journal to track habits and goals",
            "Create a filing system for your digital files",
            "Set up an online calendar for appointments and deadlines",
            "Schedule regular breaks throughout your day for better productivity",
            "Take a few minutes daily to tidy up your work area",
            "Organize your inbox into categories and folders",
            "Create a color-coded system for your work materials",
            "Track your time using a time management tool",
            "Create an online portfolio for your work or skills",
            "Set a no clutter rule in your workspace",
            "Use a note-taking app like Evernote or OneNote",
            "Start a weekly review to track progress and productivity"
        ],
        "Creative Projects": [
            "Write a blog post or article",
            "Make digital art or designs",
            "Record a video or podcast episode",
            "Start working on a personal project",
            "Make a short film or music video",
            "Create an art piece using a new medium (e.g., watercolor, charcoal)",
            "Design a logo for a fictional business or personal brand",
            "Create a photography portfolio",
            "Try a new style of painting or drawing (e.g., abstract, realism)",
            "Make a stop-motion animation video",
            "Develop a new concept for a video game or app",
            "Write a song or compose music",
            "Write a short story or novel",
            "Create a social media account to showcase your art or creativity",
            "Design a website or blog using WordPress or Wix",
            "Start a YouTube channel to showcase your creative projects",
            "Design a new logo for a company or personal brand",
            "Make a DIY craft project like a handmade journal",
            "Create a series of digital illustrations or comic strips",
            "Experiment with 3D printing or modeling",
            "Write a script or screenplay for a short film",
            "Create a digital magazine or newsletter",
            "Make a sculpture or clay model",
            "Try new creative writing techniques (e.g., freewriting, poetry)",
            "Create your own board game or card game",
            "Make a scrapbook with photos and memorabilia",
            "Create a fashion design collection",
            "Start a photography challenge (e.g., one photo a day)",
            "Record an audiobook of your favorite novel",
            "Experiment with photo editing and photo manipulation",
            "Create a digital art gallery or exhibit online",
            "Develop a creative portfolio and share it online",
            "Start a Patreon or crowdfunding page for creative projects",
            "Make a meme or viral video",
            "Design a new video game character or environment",
            "Create a printable planner or calendar",
            "Write a poem or haiku every day for a week",
            "Develop a DIY home décor project",
            "Create a business idea and develop a creative brand",
            "Start a painting challenge (e.g., 30-day painting challenge)"
        ]
    },
    "Lazy": {
        "Random & Time-Wasting": [
            "Scroll social media without purpose",
            "Watch clickbait videos or reaction content",
            "Browse shopping sites with no intention to buy",
            "Take fun online quizzes like 'What kind of bread are you?'",
            "Rearrange app icons on your phone",
            "Watch funny animal videos on YouTube",
            "Stare at random memes for hours",
            "Look at pictures of food on Instagram",
            "Follow random YouTube rabbit holes",
            "Find random conspiracy theory videos and watch",
            "Start a TikTok and browse through endless videos",
            "Play a useless mobile game for hours",
            "Watch TV shows on a streaming service for no reason",
            "Go down a Wikipedia rabbit hole on random topics",
            "Spend hours organizing your Netflix watchlist",
            "Spend time playing idle games (e.g., Clicker Heroes)",
            "Browse random blogs with no real intention",
            "Look at Pinterest pins and ideas without doing anything",
            "Replay old video games from childhood",
            "Spend hours on Reddit or Twitter",
            "Spend time reading completely unrelated articles",
            "Watch viral TikToks and save random ones",
            "Start a new social media account for no reason",
            "Spend hours looking at fashion or interior design ideas",
            "Go through the daily Facebook feed",
            "Spend time searching for the next TV series to binge-watch",
            "Look up funny reviews of products online",
            "Stalk someone’s social media profiles",
            "Look at memes for an entire hour",
            "Start collecting random things like stamps or postcards",
            "Search for random celebrity gossip or news",
            "Watch old YouTube video compilations",
            "Spend time scrolling through old Facebook memories",
            "Search for ridiculous things to laugh at on the internet",
            "Search for random Instagram pages",
            "Get lost in the 'People Also Watched' section on YouTube",
            "Spend time looking at memes for different fandoms",
            "Spend too long on “What If” question lists",
            "Search for “Weird News” online",
            "Watch people playing video games on Twitch"
        ],
        "Unfocused Tasks": [
            "Open 10 tabs and do none of them",
            "Start multiple shows and finish none",
            "Organize a drawer, then mess it up again",
            "Open 3 apps on your phone and switch between them aimlessly",
            "Go through your old photos and get distracted",
            "Open email and leave it unread",
            "Start reading a book and then forget about it",
            "Start a hobby but not continue it for long",
            "Clean the house in small sections, never finishing it",
            "Start a project and abandon it halfway",
            "Have 5 incomplete drafts of blog posts",
            "Spend an hour on your phone but not do anything productive",
            "Start a puzzle but don’t complete it",
            "Rearrange things without finishing it",
            "Move things around your desk without a purpose",
            "Leave multiple messages half written",
            "Open a website, but don't know why",
            "Start a conversation but forget about it",
            "Make a to-do list but never cross things off",
            "Pick up a hobby and then forget it exists",
            "Try to clean the house but leave every room halfway done",
            "Begin an online course and not finish the lessons",
            "Put a movie on and not even watch it",
            "Start a game and then lose interest after 5 minutes",
            "Start an online shopping cart but never check out",
            "Look for random recipes and then not cook",
            "Open an app and get distracted immediately",
            "Start a creative project and not finish it",
            "Buy supplies for a hobby but never use them",
            "Start exercising but stop after 5 minutes",
            "Spend 10 minutes organizing and 30 minutes procrastinating",
            "Organize a drawer only to add more things to it later",
            "Pick out a series to binge-watch but fall asleep instead"
        ]
    },
    "Entertainment": {
        "Digital Entertainment": [
            "Watch a movie, series, or anime",
            "Play a video or mobile game",
            "Explore new music or YouTube channels",
            "Watch a live stream on Twitch or YouTube",
            "Browse Netflix or Hulu for hours",
            "Watch a new documentary or documentary series",
            "Binge-watch a random series for a day",
            "Listen to a new album or playlist",
            "Find a new favorite podcast",
            "Watch an old TV show you loved",
            "Rewatch your favorite movies",
            "Explore a new genre of music",
            "Watch a stand-up comedy show",
            "Watch a cooking show or YouTube cooking tutorial",
            "Listen to an audiobook while relaxing",
            "Discover new YouTube creators",
            "Download a new mobile game and get hooked",
            "Watch a film festival or indie movie",
            "Attend a virtual concert or theater event",
            "Play multiplayer games with friends",
            "Try a streaming service you haven't used before",
            "Watch random reaction videos",
            "Listen to a live radio broadcast online",
            "Try out new podcasts on various topics",
            "Watch vlogs of people traveling around the world",
            "Explore podcasts on self-improvement or mental health",
            "Watch series or movies from other countries",
            "Explore different genres of movies you usually don't watch",
            "Watch trailers of upcoming movies",
            "Follow your favorite celebrity's live updates",
            "Explore YouTube’s “You Might Like” section",
            "Listen to a podcast episode from a random category",
            "Watch old music videos from the 80s or 90s",
            "Try a new streaming platform like Disney+ or Amazon Prime",
            "Play games on your gaming console or mobile",
            "Download and play a nostalgic retro game"
        ],
        "Social Entertainment": [
            "Play online games with friends",
            "Join a fun Discord community or voice chat",
            "Host or join a virtual trivia/game night",
            "Start a group chat for movie recommendations",
            "Play board games online with family or friends",
            "Join an online book club or reading group",
            "Watch a live sports event together with friends",
            "Join a virtual concert with friends",
            "Host a Zoom or Google Meet call with friends",
            "Start a Dungeons & Dragons campaign with friends",
            "Host a virtual movie marathon",
            "Play online charades or Pictionary",
            "Start a virtual workout challenge with friends",
            "Participate in a virtual cooking class",
            "Join a podcast club or discussion group",
            "Join a virtual game tournament",
            "Host an online party or themed event",
            "Join a fun online quiz or trivia game",
            "Chat with old friends on a video call",
            "Host a virtual happy hour with friends",
            "Join an online challenge like a meme challenge",
            "Have a virtual karaoke night with friends",
            "Host a virtual book club meeting",
            "Join a virtual yoga or fitness group",
            "Participate in an online contest or sweepstakes",
            "Join a hobby group on Reddit or Facebook",
            "Start a group project with your friends online",
            "Join an online art or creative community",
            "Organize a virtual potluck with friends",
            "Host a virtual talent show",
            "Share funny or cool memes with your friends",
            "Create a virtual watch party for a movie or series"
        ],
        "Creative Fun": [
            "Write a short story or make a comic",
            "Try a drawing challenge (e.g., eyes closed)",
            "Create a funny meme or parody video",
            "Try making a viral video or challenge",
            "Create a digital art masterpiece",
            "Draw a portrait of your favorite celebrity",
            "Write a poem or haiku",
            "Make a DIY art project",
            "Create a short film or animation",
            "Learn to draw cartoons or characters",
            "Make a fun character or avatar for yourself",
            "Experiment with new styles of painting",
            "Create a new meme template",
            "Design a fun board game",
            "Make a music video for a song you like",
            "Create a time-lapse video of your day",
            "Write a creative script for a short film",
            "Try making a mini sculpture or model",
            "Design a custom t-shirt or hoodie",
            "Create a photo collage",
            "Draw or paint a landscape or still life",
            "Make a comic strip of your day",
            "Create a creative video series",
            "Design a unique logo or brand for fun",
            "Try a new digital art style",
            "Make a paper airplane and see how far it flies",
            "Start a painting challenge and complete it in a week",
            "Make your own comic book",
            "Create a fun challenge for your friends",
            "Draw a picture with no reference",
            "Create a short animation or flipbook",
            "Start a zine or self-published book",
            "Experiment with 3D modeling software",
            "Design your own greeting card collection",
            "Make a clay sculpture or pottery",
            "Create a series of photo projects"
        ]
    },
    "Relaxation": {
        "Mind & Body": [
            "Take a nap or rest with calming music",
            "Meditate or do breathwork",
            "Practice yoga or light stretching",
            "Take a hot shower or bath",
            "Do a skincare/self-care routine",
            "Do deep breathing exercises",
            "Practice mindfulness or focus on your breathing",
            "Spend time in nature, take a walk in the park",
            "Use a relaxation app to guide you",
            "Stretch your body to relieve tension",
            "Try progressive muscle relaxation",
            "Take a break in a quiet room or space",
            "Do a light workout like Pilates or yoga",
            "Take a digital detox for an hour",
            "Listen to a meditation podcast",
            "Try Tai Chi or Qigong for gentle movement",
            "Light a candle and unwind",
            "Do some gentle, calming exercises for flexibility",
            "Read or listen to soothing books",
            "Use a foam roller for muscle relaxation",
            "Take a scenic drive and enjoy the surroundings",
            "Sip on chamomile tea to relax",
            "Visit a sauna or steam room if available",
            "Do a quick guided meditation session",
            "Spend time in nature with no distractions",
            "Relax with a hot cup of herbal tea",
            "Listen to ocean waves or nature sounds for calmness",
            "Take a slow walk and enjoy the surroundings",
            "Try progressive muscle relaxation before sleep",
            "Do breathing exercises to calm your mind",
            "Take a power nap to recharge",
            "Enjoy a quiet evening with a warm blanket",
            "Unwind with a guided body scan meditation",
            "Do a light walk outside to relax"
        ],
        "Calm & Low-Energy": [
            "Listen to chill music or nature sounds",
            "Read fiction or poetry",
            "Light a candle and relax in silence",
            "Sit outside and watch the sky",
            "Make tea or coffee and sip slowly",
            "Sit in a cozy chair and read a book",
            "Listen to relaxing music or instrumental jazz",
            "Take a moment to reflect or journal your thoughts",
            "Try a guided relaxation video",
            "Go for a walk in a quiet, peaceful area",
            "Relax by the fireplace or heater",
            "Try to clear your mind and focus on nothing",
            "Sip a warm drink while watching the rain",
            "Spend some time meditating or thinking deeply",
            "Do some mindful listening to ambient sounds",
            "Curl up with a blanket and relax",
            "Enjoy a cup of herbal tea while reading",
            "Listen to an audiobook while lying down",
            "Take a deep breath and let go of stress",
            "Look outside at the stars or nature",
            "Lie down and just focus on your breathing",
            "Do a calm and soothing coloring activity",
            "Sit on a bench in a park and enjoy nature's sounds",
            "Watch a gentle, slow-paced movie or show",
            "Try a relaxing puzzle or brain teaser",
            "Spend a few moments reflecting on your day",
            "Stare out the window and enjoy the view",
            "Lie in bed and let your mind wander",
            "Do some gentle stretching and breathing",
            "Take a mindful walk without distractions",
            "Try a calming guided imagery exercise",
            "Do some light reading in a peaceful setting",
            "Sit quietly in a room with soft lighting"
        ]
    }
}
